#application: jackieeric
runtime: python27
api_version: 1
threadsafe: yes

libraries:
  - name: jinja2
    version: "2.6"
  - name: webapp2
    version: "2.5.2"

handlers:

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /img/(.+\.webp)
  mime_type: image/webp
  static_files: img/\1
  upload: img/(.+\.webp)
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /sw.js
  static_files: js/sw.js
  upload: /sw.js
  secure: always

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /dexecure-(.*).js
  static_files: js/dexecure-\1.js
  upload: /dexecure-(.*).js
  secure: always

#- url: /manifest.json
#  static_files: manifest.json
#  upload: manifest.json
#  mime_type: application/manifest+json
#  secure: always

- url: /\.well\-known\/acme\-challenge\/.*
  script: letsencrypt.app
  secure: always

- url: /rsvp_list
  script: server.app
  secure: always
  login: admin

- url: .*
  script: server.app
  secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.graffle$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - gulpfile.js
  - test*
  - bower_components/[^/]+/bower_components/.*$
  - bower_components/(.+/)+(test/|demo/|README|AUTHORS|CONTRIBUTING|PATENTS|Makefile)
  - node_modules/
  - img/unused/
